"""HotelHiltonDBV0.0.

Revision ID: 5634330a7d89
Revises: 365d36a7e364
Create Date: 2025-03-27 17:06:46.868931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5634330a7d89'
down_revision: Union[str, None] = '365d36a7e364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('role_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'customer', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'role_id')
    # ### end Alembic commands ###
